#!/usr/bin/env python

"""
Publish and tag a given file, with title and body extracted from the HTML
markup of the file.  The corresponding draft page, if any, will be deleted if
the publish request succeeds.

Usage: publish [-l] [-t tagstring] [-f] filepath

By default, requests are made to {APPID}.appspot.com. The script will fail if
content already exists on the given path, unless -f is given to force update.

Options:
    -l    make requests to localhost:8080
    -t    use the supplied tags, which should be given as a comma-separated string
    -f    force update
"""

import BeautifulSoup
import getopt
import sys

host = None
forced = False
tags = []

opts, args = getopt.getopt(sys.argv[1:], 'flt:')
for o, v in opts:
	if o == '-l':
		host = 'localhost:8080'
	elif o == '-t':
		tags = set(map(unicode, v.split(',')))
	elif o == '-f':
		forced = True
filename = args[0]

import remote
remote.attach(host)

import models


soup = BeautifulSoup.BeautifulSoup(open(filename).read())
title = unicode(soup.title.string)
body = u''.join(unicode(s) for s in soup.body.contents if s)

# Delegate to the shared publish routine so the command line and the admin
# handler write static content, manage the cache, clear drafts and regenerate
# dependent pages through exactly the same code path.
try:
	models.publish_post(title, body, tags, force=forced)
except models.PathExistsError, e:
	sys.exit("error: content exists on path %s, use -f to force update" % e)
