#!/usr/bin/env python

"""
Publish and tag a given file, with title and body extracted from the HTML
markup of the file.  The corresponding draft page, if any, will be deleted if
the publish request succeed.

Usage: publish [-l] [-t tagstring] [-f] filepath

By default, requests are made to {APPID}.appspot.com. The script will fail if
content already exists on the given path.

Options:
      -l    make requests to localhost:8080
      -t    use the supplied tags, which should be given as a comma-separated string
      -f    force update
"""

import BeautifulSoup
import datetime
import getopt
import os
import sys

host = None
forced = False
tags = []

opts, args = getopt.getopt(sys.argv[1:], 'flt:')
for o, v in opts:
    if o == '-l':
        host = 'localhost:8080'
    elif o == '-t':
        tags = set(map(unicode, v.split(',')))
    elif o == '-f':
        forced = True
filename = args[0]

import remote
remote.attach(host)

import config
import models
import utils


soup = BeautifulSoup.BeautifulSoup(open(filename).read())
title = unicode(soup.title.string)
body = u''.join(unicode(s) for s in soup.body.contents if s)
slug = utils.slugify(title)

# Look up an existing published post by slug.  This is safe across
# month boundaries (unlike path-based lookup which depends on the
# current date and would miss posts published in a different month).
existing = None
for post in models.BlogPost.all().order('-published'):
    if post.path and utils.slugify(post.title) == slug:
        existing = post
        break

if existing:
    if not forced:
        sys.exit("error: post already exists at %s, use -f to force update"
                 % existing.path)
    existing.title = title
    existing.body = body
    existing.tags = tags
    # publish() handles: updated timestamp, dependency regeneration,
    # and draft cleanup.
    existing.publish()
else:
    post = models.BlogPost(
        title=title,
        body=body,
        tags=tags,
        published=datetime.datetime.now()
    )
    # publish() handles: path allocation, timestamps (published + updated),
    # dependency regeneration, and draft cleanup.
    post.publish()
